### ISSUE TITLE
Check this out!

### ISSUE THREAD

**Issue by johnwaves** [danieeeld2/danieeeld2.github.io#1]
Está genial el portfolio, pero no veo ningún issue al cual estés referenciando los cambios.
Por otra parte, el dark mode sería una pasada si lo pudieses aplicar 😆😉.

**Comment by danieeeld2** [comment]
> Está genial el portfolio, pero no veo ningún issue al cual estés referenciando los cambios. Por otra parte, el dark mode sería una pasada si lo pudieses aplicar 😆😉.

jajajaja es que he copiado la plantilla pero no acabé de hacerlo, pero lo tengo que tener en publico para que funcione el action del deploy 🤣🤣. Esperemos que JJ no se pase por este repo jajaja

**Comment by johnwaves** [comment]
Muy bien
